version: "3.9"

services:
  app:
    build: .
    container_name: app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db/db
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"

  test_db:
      image: postgres:15
      container_name: test_db
      environment:
        POSTGRES_USER: test_user
        POSTGRES_PASSWORD: test_password
        POSTGRES_DB: test_db
      ports:
        - "5433:5432"