version: "3.9"

services:
  app:
    build: .
    container_name: app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db/db
    depends_on:
      - db
    command: >
      sh -c "/app/wait-for-it.sh db:5432 -- alembic upgrade head &&
      uvicorn app.main:app --host 0.0.0.0 --port 8000"

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  test_db:
    image: postgres:15
    container_name: test_db
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    ports:
      - "5433:5432"
    volumes:
      - test_db_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8080:80" # Проброс порта для доступа к фронтенду
    depends_on:
      - app
    restart: always
    networks:
      - quartaltech_network

networks:
  quartaltech_network:
    driver: bridge