"""apartment id

Revision ID: aa04f10848a4
Revises: 52a22ac28cbc
Create Date: 2024-11-19 15:09:29.586177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa04f10848a4'
down_revision = '52a22ac28cbc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
